<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DTU3KAA" failures="2" tests="2" name="cucumberOptions.TestNGTestRunner" time="42.439" errors="0" timestamp="2022-10-10T12:13:42 IST" skipped="0">
  <testcase classname="cucumberOptions.TestNGTestRunner" name="runScenario" time="21.225">
    <failure message="expected [no] but found [yes]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [no] but found [yes]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.Home.user_logged_in_sucessfully(Home.java:38)
at ✽.user logged in sucessfully(file:///C:/Users/vasudha/Documents/Work/Memorres/clinimise/src/test/java/features/Login.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="cucumberOptions.TestNGTestRunner" name="runScenario" time="21.214">
    <failure message="expected [no] but found [yes]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [no] but found [yes]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.Home.user_logged_in_sucessfully(Home.java:38)
at ✽.user logged in sucessfully(file:///C:/Users/vasudha/Documents/Work/Memorres/clinimise/src/test/java/features/Login.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- cucumberOptions.TestNGTestRunner -->
